
services:
  db:
    image: postgres:14.5
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rate_app
    ports:
      - "5432:5432"

volumes:
  pgdata: