# Generated by Django 5.1.4 on 2024-12-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
    ]
