# Generated by Django 5.1.4 on 2024-12-11 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_post_user_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_average', models.FloatField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.post')),
            ],
        ),
    ]
