# Generated by Django 5.1.4 on 2024-12-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_ratingaverage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingaverage',
            old_name='end',
            new_name='from_time',
        ),
        migrations.RenameField(
            model_name='ratingaverage',
            old_name='start',
            new_name='to_time',
        ),
    ]
