# Generated by Django 5.1.4 on 2024-12-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_rename_end_ratingaverage_from_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingaverage',
            name='user_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
