# Generated by Django 5.1.4 on 2024-12-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0006_ratingaverage_user_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingaverage',
            name='user_count',
        ),
    ]
