# Generated by Django 5.1.4 on 2024-12-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0007_remove_ratingaverage_user_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='computed',
            field=models.BooleanField(default=False),
        ),
    ]
