# Generated by Django 5.1.4 on 2024-12-12 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0008_rating_computed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingaverage',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='ratingaverage',
            name='to_time',
        ),
        migrations.AddField(
            model_name='ratingaverage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
